project_id = "mjhsvrksrmcemhbglfkm"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://mjhsvrksrmcemhbglfkm.lovableproject.com"]

[functions.auth-login]
verify_jwt = false

[functions.auth-refresh]
verify_jwt = false

[functions.auth-validate]
verify_jwt = false

[functions.geocode-reverse]
verify_jwt = false

[functions.create-organization-account]
verify_jwt = false